### ISSUE TITLE
Use user display name instead of their unique name

### ISSUE THREAD

**Issue by LoneWolfHT** [MT-CTF/ctf-discord-bot#16]
e.g LandarVargan instead of landarvargan 
![image](https://github.com/MT-CTF/ctf-discord-bot/assets/28972859/e9288d71-a5bc-47ea-8403-a2d123acf77d)

**Comment by AFCMS** [comment]
Need upcoming `Discord.js` v14.12 (https://github.com/discordjs/discord.js/pull/9512) to be done properly.

Will look into it.

**Comment by AFCMS** [comment]
`GuildMember.displayName` currently return the nickname or the username if nickname doesn't exist for the guild

The PR seem to make this property use the new `User.displayName` property instead of the username, so we can migrate the code to use `GuildMember.displayName` and then just bump to v14.12 when available.

Will work on it.
